# Archivo de configuración para el acceso
# a la base de datos.
# @author Angel Barrientos Cruz <uetiko@gmail.com>

base:
  usuario : delphos
  passwd : delphos
  host : 127.0.0.1
  puerto : 3306
  dbname : delphos